<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Acerca',
    'Actions' => 'Acciones',
    'Activate Pilots' => 'Activar Pilotos',
    'Admin' => 'Admin',
    'Aircraft Configurations' => 'Configuraciones de Aeronaves',
    'Aircraft Types' => 'Tipos de Aeronaves',
    'Aircrafts' => 'Aeronaves',
    'Airports' => 'Aeropuertos',
    'Countries' => 'Países',
    'Flights' => 'Vuelos',
    'Home' => 'Inicio',
    'List FPLs' => 'Listar FPLs',
    'Login' => 'Login',
    'Logout' => 'Logout',
    'Manage Images' => 'Gestionar Imágenes',
    'Move Pilot' => 'Mover Piloto',
    'Operations' => 'Operaciones',
    'Pilots' => 'Pilotos',
    'Ranks' => 'Rangos',
    'Routes' => 'Rutas',
    'Rules' => 'Reglamentación',
    'School' => 'Escuela',
    'Staff' => 'Staff',
    'Submit FPL' => 'Enviar FPL',
    'Tours' => 'Tours',
    'Validate Flights' => 'Validación de Vuelos',
    'Validations' => 'Validaciones',
];
