<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Acerca',
    'Actions' => 'Acciones',
    'Activate Pilots' => 'Activar Pilotos',
    'Admin' => 'Admin',
    'Aircraft Configuration' => 'Configuración de la Aeronave',
    'Aircraft Configurations' => 'Configuraciones de Aeronaves',
    'Aircraft Type' => 'Tipo de Aeronave',
    'Aircraft Types' => 'Tipos de Aeronaves',
    'Aircrafts' => 'Aeronaves',
    'Airport (ICAO)' => 'Aeropuerto (ICAO)',
    'Airport Location' => 'Localización del Aeropuerto',
    'Airports' => 'Aeropuertos',
    'Are you sure you want to delete this item?' => '¿Estás seguro de que deseas eliminar este elemento?',
    'Cargo Capacity' => 'Capacidad de Cargo',
    'City' => 'Ciudad',
    'Countries' => 'Países',
    'Country' => 'País',
    'Create Aircraft' => 'Crear Aeronave',
    'Create Aircraft Configuration' => 'Crear Configuración de Aeronave',
    'Create Aircraft Type' => 'Crear Tipo de Aeronave',
    'Create Airport' => 'Crear Aeropuerto',
    'Create Country' => 'Crear País',
    'Delete' => 'Eliminar',
    'Flag' => 'Bandera',
    'Flights' => 'Vuelos',
    'Home' => 'Inicio',
    'Hours Flown' => 'Horas de Vuelo',
    'ICAO Code' => 'Código ICAO',
    'ID' => 'ID',
    'ISO2 Code' => 'Código ISO2',
    'Icao Code' => 'Código ICAO',
    'Icao Type Code' => 'Código de Tipo ICAO',
    'Latitude' => 'Latitud',
    'List FPLs' => 'Listar FPLs',
    'Location' => 'Localización',
    'Login' => 'Login',
    'Logout' => 'Logout',
    'Longitude' => 'Longitud',
    'Manage Images' => 'Gestionar Imágenes',
    'Max Range (NM)' => 'Máximo Alcance (NM)',
    'Move' => 'Mover',
    'Move Aircraft' => 'Mover Aeronave',
    'Move Pilot' => 'Mover Piloto',
    'Name' => 'Nombre',
    'Operations' => 'Operaciones',
    'Pax Capacity' => 'Capacidad de Pasajeros',
    'Pilots' => 'Pilotos',
    'Please enter the ICAO code of the airport to move this aircraft.' => 'Por favor introduzca el ICAO del aeropuerto al que desea mover esta aeronave.',
    'Ranks' => 'Rangos',
    'Registration' => 'Matrícula',
    'Routes' => 'Rutas',
    'Rules' => 'Reglamentación',
    'Save' => 'Guardar',
    'School' => 'Escuela',
    'Select Aircraft Configuration' => 'Seleccione una Configuración de Aeronave',
    'Select Aircraft Type' => 'Seleccione un Tipo de Aeronave',
    'Select Country' => 'Seleccione un País',
    'Staff' => 'Staff',
    'Submit FPL' => 'Enviar FPL',
    'Tours' => 'Tours',
    'Update' => 'Modificar',
    'Update Aircraft' => 'Modificar Aeronave',
    'Update Aircraft Configuration' => 'Modificar Configuración de Aeronave',
    'Update Aircraft Type' => 'Modificar Tipo de Aeronave',
    'Update Airport' => 'Modificar Aeropuerto',
    'Update Country' => 'Modificar País',
    'Validate Flights' => 'Validación de Vuelos',
    'Validations' => 'Validaciones',
];
