INSERT INTO country (iso2_code,name) VALUES
	 ('AF','Afghanistan'),
	 ('AX','Aland Islands'),
	 ('AL','Albania'),
	 ('DZ','Algeria'),
	 ('AS','American Samoa'),
	 ('AD','Andorra'),
	 ('AO','Angola'),
	 ('AI','Anguilla'),
	 ('AQ','Antarctica'),
	 ('AG','Antigua and Barbuda');
INSERT INTO country (iso2_code,name) VALUES
	 ('AR','Argentina'),
	 ('AM','Armenia'),
	 ('AW','Aruba'),
	 ('AU','Australia'),
	 ('AT','Austria'),
	 ('AZ','Azerbaijan'),
	 ('BS','Bahamas'),
	 ('BH','Bahrain'),
	 ('BD','Bangladesh'),
	 ('BB','Barbados');
INSERT INTO country (iso2_code,name) VALUES
	 ('BY','Belarus'),
	 ('BE','Belgium'),
	 ('BZ','Belize'),
	 ('BJ','Benin'),
	 ('BM','Bermuda'),
	 ('BT','Bhutan'),
	 ('BO','Bolivia'),
	 ('BQ','Bonaire, Sint Eustatius and Saba'),
	 ('BA','Bosnia and Herzegovina'),
	 ('BW','Botswana');
INSERT INTO country (iso2_code,name) VALUES
	 ('BV','Bouvet Island'),
	 ('BR','Brazil'),
	 ('IO','British Indian Ocean Territory'),
	 ('BN','Brunei'),
	 ('BG','Bulgaria'),
	 ('BF','Burkina Faso'),
	 ('BI','Burundi'),
	 ('KH','Cambodia'),
	 ('CM','Cameroon'),
	 ('CA','Canada');
INSERT INTO country (iso2_code,name) VALUES
	 ('CV','Cape Verde'),
	 ('KY','Cayman Islands'),
	 ('CF','Central African Republic'),
	 ('TD','Chad'),
	 ('CL','Chile'),
	 ('CN','China'),
	 ('CX','Christmas Island'),
	 ('CC','Cocos (Keeling) Islands'),
	 ('CO','Colombia'),
	 ('KM','Comoros');
INSERT INTO country (iso2_code,name) VALUES
	 ('CG','Congo'),
	 ('CK','Cook Islands'),
	 ('CR','Costa Rica'),
	 ('CI','Cote d''ivoire (Ivory Coast)'),
	 ('HR','Croatia'),
	 ('CU','Cuba'),
	 ('CW','Curacao'),
	 ('CY','Cyprus'),
	 ('CZ','Czech Republic'),
	 ('CD','Democratic Republic of the Congo');
INSERT INTO country (iso2_code,name) VALUES
	 ('DK','Denmark'),
	 ('DJ','Djibouti'),
	 ('DM','Dominica'),
	 ('DO','Dominican Republic'),
	 ('EC','Ecuador'),
	 ('EG','Egypt'),
	 ('SV','El Salvador'),
	 ('GQ','Equatorial Guinea'),
	 ('ER','Eritrea'),
	 ('EE','Estonia');
INSERT INTO country (iso2_code,name) VALUES
	 ('ET','Ethiopia'),
	 ('FK','Falkland Islands (Malvinas)'),
	 ('FO','Faroe Islands'),
	 ('FJ','Fiji'),
	 ('FI','Finland'),
	 ('FR','France'),
	 ('GF','French Guiana'),
	 ('PF','French Polynesia'),
	 ('TF','French Southern Territories'),
	 ('GA','Gabon');
INSERT INTO country (iso2_code,name) VALUES
	 ('GM','Gambia'),
	 ('GE','Georgia'),
	 ('DE','Germany'),
	 ('GH','Ghana'),
	 ('GI','Gibraltar'),
	 ('GR','Greece'),
	 ('GL','Greenland'),
	 ('GD','Grenada'),
	 ('GP','Guadaloupe'),
	 ('GU','Guam');
INSERT INTO country (iso2_code,name) VALUES
	 ('GT','Guatemala'),
	 ('GG','Guernsey'),
	 ('GN','Guinea'),
	 ('GW','Guinea-Bissau'),
	 ('GY','Guyana'),
	 ('HT','Haiti'),
	 ('HM','Heard Island and McDonald Islands'),
	 ('HN','Honduras'),
	 ('HK','Hong Kong'),
	 ('HU','Hungary');
INSERT INTO country (iso2_code,name) VALUES
	 ('IS','Iceland'),
	 ('IN','India'),
	 ('ID','Indonesia'),
	 ('IR','Iran'),
	 ('IQ','Iraq'),
	 ('IE','Ireland'),
	 ('IM','Isle of Man'),
	 ('IL','Israel'),
	 ('IT','Italy'),
	 ('JM','Jamaica');
INSERT INTO country (iso2_code,name) VALUES
	 ('JP','Japan'),
	 ('JE','Jersey'),
	 ('JO','Jordan'),
	 ('KZ','Kazakhstan'),
	 ('KE','Kenya'),
	 ('KI','Kiribati'),
	 ('XK','Kosovo'),
	 ('KW','Kuwait'),
	 ('KG','Kyrgyzstan'),
	 ('LA','Laos');
INSERT INTO country (iso2_code,name) VALUES
	 ('LV','Latvia'),
	 ('LB','Lebanon'),
	 ('LS','Lesotho'),
	 ('LR','Liberia'),
	 ('LY','Libya'),
	 ('LI','Liechtenstein'),
	 ('LT','Lithuania'),
	 ('LU','Luxembourg'),
	 ('MO','Macao'),
	 ('MK','Macedonia');
INSERT INTO country (iso2_code,name) VALUES
	 ('MG','Madagascar'),
	 ('MW','Malawi'),
	 ('MY','Malaysia'),
	 ('MV','Maldives'),
	 ('ML','Mali'),
	 ('MT','Malta'),
	 ('MH','Marshall Islands'),
	 ('MQ','Martinique'),
	 ('MR','Mauritania'),
	 ('MU','Mauritius');
INSERT INTO country (iso2_code,name) VALUES
	 ('YT','Mayotte'),
	 ('MX','Mexico'),
	 ('FM','Micronesia'),
	 ('MD','Moldava'),
	 ('MC','Monaco'),
	 ('MN','Mongolia'),
	 ('ME','Montenegro'),
	 ('MS','Montserrat'),
	 ('MA','Morocco'),
	 ('MZ','Mozambique');
INSERT INTO country (iso2_code,name) VALUES
	 ('MM','Myanmar (Burma)'),
	 ('NA','Namibia'),
	 ('NR','Nauru'),
	 ('NP','Nepal'),
	 ('NL','Netherlands'),
	 ('NC','New Caledonia'),
	 ('NZ','New Zealand'),
	 ('NI','Nicaragua'),
	 ('NE','Niger'),
	 ('NG','Nigeria');
INSERT INTO country (iso2_code,name) VALUES
	 ('NU','Niue'),
	 ('NF','Norfolk Island'),
	 ('KP','North Korea'),
	 ('MP','Northern Mariana Islands'),
	 ('NO','Norway'),
	 ('OM','Oman'),
	 ('PK','Pakistan'),
	 ('PW','Palau'),
	 ('PS','Palestine'),
	 ('PA','Panama');
INSERT INTO country (iso2_code,name) VALUES
	 ('PG','Papua New Guinea'),
	 ('PY','Paraguay'),
	 ('PE','Peru'),
	 ('PH','Phillipines'),
	 ('PN','Pitcairn'),
	 ('PL','Poland'),
	 ('PT','Portugal'),
	 ('PR','Puerto Rico'),
	 ('QA','Qatar'),
	 ('RE','Reunion');
INSERT INTO country (iso2_code,name) VALUES
	 ('RO','Romania'),
	 ('RU','Russia'),
	 ('RW','Rwanda'),
	 ('BL','Saint Barthelemy'),
	 ('SH','Saint Helena'),
	 ('KN','Saint Kitts and Nevis'),
	 ('LC','Saint Lucia'),
	 ('MF','Saint Martin'),
	 ('PM','Saint Pierre and Miquelon'),
	 ('VC','Saint Vincent and the Grenadines');
INSERT INTO country (iso2_code,name) VALUES
	 ('WS','Samoa'),
	 ('SM','San Marino'),
	 ('ST','Sao Tome and Principe'),
	 ('SA','Saudi Arabia'),
	 ('SN','Senegal'),
	 ('RS','Serbia'),
	 ('SC','Seychelles'),
	 ('SL','Sierra Leone'),
	 ('SG','Singapore'),
	 ('SX','Sint Maarten');
INSERT INTO country (iso2_code,name) VALUES
	 ('SK','Slovakia'),
	 ('SI','Slovenia'),
	 ('SB','Solomon Islands'),
	 ('SO','Somalia'),
	 ('ZA','South Africa'),
	 ('GS','South Georgia and the South Sandwich Islands'),
	 ('KR','South Korea'),
	 ('SS','South Sudan'),
	 ('ES','Spain'),
	 ('LK','Sri Lanka');
INSERT INTO country (iso2_code,name) VALUES
	 ('SD','Sudan'),
	 ('SR','Suriname'),
	 ('SJ','Svalbard and Jan Mayen'),
	 ('SZ','Swaziland'),
	 ('SE','Sweden'),
	 ('CH','Switzerland'),
	 ('SY','Syria'),
	 ('TW','Taiwan'),
	 ('TJ','Tajikistan'),
	 ('TZ','Tanzania');
INSERT INTO country (iso2_code,name) VALUES
	 ('TH','Thailand'),
	 ('TL','Timor-Leste (East Timor)'),
	 ('TG','Togo'),
	 ('TK','Tokelau'),
	 ('TO','Tonga'),
	 ('TT','Trinidad and Tobago'),
	 ('TN','Tunisia'),
	 ('TR','Turkey'),
	 ('TM','Turkmenistan'),
	 ('TC','Turks and Caicos Islands');
INSERT INTO country (iso2_code,name) VALUES
	 ('TV','Tuvalu'),
	 ('UG','Uganda'),
	 ('UA','Ukraine'),
	 ('AE','United Arab Emirates'),
	 ('GB','United Kingdom'),
	 ('US','United States'),
	 ('UM','United States Minor Outlying Islands'),
	 ('UY','Uruguay'),
	 ('UZ','Uzbekistan'),
	 ('VU','Vanuatu');
INSERT INTO country (iso2_code,name) VALUES
	 ('VA','Vatican City'),
	 ('VE','Venezuela'),
	 ('VN','Vietnam'),
	 ('VG','Virgin Islands, British'),
	 ('VI','Virgin Islands, US'),
	 ('WF','Wallis and Futuna'),
	 ('EH','Western Sahara'),
	 ('YE','Yemen'),
	 ('ZM','Zambia'),
	 ('ZW','Zimbabwe');
