<?php
namespace app\commands;

use app\config\Config;
use yii\console\Controller;
use yii\console\ExitCode;

class FlightReportController extends Controller
{
    /**
     * This command list the folders of the pending flight report to be analyzed
     * @return int Exit code
     */
    public function actionListPending()
    {

        $storagePath = Config::get('chunks_storage_path');

        $flightsPendingToAnalyze = \app\models\Flight::find()
        ->where(['status' => 'S'])
        ->all();

        foreach ($flightsPendingToAnalyze as $flight) {
            $reportId = $flight->flightReport->id;

            $flightReportPath = $storagePath . DIRECTORY_SEPARATOR . $reportId;
            $this->stdout("{$flightReportPath}\n");
        }

        return ExitCode::OK;
    }

    /**
     * Import events and analysis generated by mam-analyzer for a flight report.
     */
    public function actionImportReportAnalysis()
    {
        $this->stdout("Importing analyzed report...\n");

        // TODO: buscar en /data/processed/ los json ya analizados
        // TODO: parsear el contenido
        // TODO: poblar tablas en DB con ActiveRecord
        // TODO: actualizar estado del vuelo

        $this->stdout("Done.\n");
        return ExitCode::OK;
    }
}
